version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: dockers/Dockerfile_backend
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=spectrum
    #depends_on:
    #- database

  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: dockers/Dockerfile_frontend
    depends_on:
      #- database
      - backend

  #database:
  #  container_name: database
  #  build:
  #    context: ./
  #    dockerfile: Dockerfile_database


