FROM python:3.12

WORKDIR /backend
COPY backend .
USER root

# Update apt sources and install dependencies
RUN apt-get update && apt-get install -y python3-soapysdr soapysdr-module-all && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv opt/venv --system-site-packages
ENV PATH="opt/venv/bin:$PATH"
RUN pip install --no-cache-dir -r requirements.txt

#ENTRYPOINT ["top", "-b"]
# Default command
CMD ["python3", "app.py"]
