FROM python:3.12

WORKDIR /backend
COPY backend .

RUN sudo apt install python3-soapysdr soapysdr-module-all &&\
    python3 -m venv venv --system-site-packages &&\
    source venv/bin/activate && pip install -r requirements.txt

RUN python3 app.py
